# Generated by Django 4.2.16 on 2024-11-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
