# Generated by Django 4.2.16 on 2024-11-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='movie_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='movie_poster_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='movie_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='movie_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
