# Generated by Django 4.2.16 on 2024-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_movie_id_article_movie_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='movie_poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
